# Imports:
<ol>
    importing libraries that gonna be used in the model
</ol>    


In [1]:
import pandas as pd
import numpy as np
import warnings
import seaborn as sns
import matplotlib.pyplot as plt
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from scipy.sparse import hstack
from sklearn.svm import LinearSVR

In [2]:
df = pd.read_csv("C:/Users/dell/OneDrive/Desktop/AMIT ML/Pandas/instadata.csv",encoding='utf-8', encoding_errors="replace")

In [3]:
df.head()

Impressions  From Home  From Hashtags  From Explore  From Other  Saves  \
0         3920       2586           1028           619          56     98   
1         5394       2727           1838          1174          78    194   
2         4021       2085           1188             0         533     41   
3         4528       2700            621           932          73    172   
4         2518       1704            255           279          37     96   

   Comments  Shares  Likes  Profile Visits  Follows  \
0         9       5    162              35        2   
1         7      14    224              48       10   
2        11       1    131              62       12   
3        10       7    213              23        8   
4         5       4    123               8        0   

                                             Caption  \
0  Here are some of the most important data visua...   
1  Here are some of the best data science project...   
2  Learn how to train a machine learning model an...   
3  Here�s how you can write a Python program to d...   
4  Plotting annotations while visualizing your da...   

                                            Hashtags  
0  #finance�#money�#business�#investing�#investme...  
1  #healthcare�#health�#covid�#data�#datascience�...  
2  #data�#datascience�#dataanalysis�#dataanalytic...  
3  #python�#pythonprogramming�#pythonprojects�#py...  
4  #datavisualization�#datascience�#data�#dataana...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Impressions     119 non-null    int64 
 1   From Home       119 non-null    int64 
 2   From Hashtags   119 non-null    int64 
 3   From Explore    119 non-null    int64 
 4   From Other      119 non-null    int64 
 5   Saves           119 non-null    int64 
 6   Comments        119 non-null    int64 
 7   Shares          119 non-null    int64 
 8   Likes           119 non-null    int64 
 9   Profile Visits  119 non-null    int64 
 10  Follows         119 non-null    int64 
 11  Caption         119 non-null    object
 12  Hashtags        119 non-null    object
dtypes: int64(11), object(2)
memory usage: 12.2+ KB


In [5]:
df.notnull().value_counts()

Impressions  From Home  From Hashtags  From Explore  From Other  Saves  Comments  Shares  Likes  Profile Visits  Follows  Caption  Hashtags
True         True       True           True          True        True   True      True    True   True            True     True     True        119
Name: count, dtype: int64

# cleaning the data set
<ol>
dropping the duplicates and Null-values
</ol>

In [6]:
df.drop_duplicates(inplace=True)

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(102, 13)

# applying vectorizer:
<ol>
To converting the caption and hashtags columns into sparse matrix

In [10]:
vector = TfidfVectorizer()

In [11]:
Z = vector.fit_transform(df["Caption"])

In [12]:
Z

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2415 stored elements and shape (102, 551)>

In [13]:
V = vector.fit_transform(df["Hashtags"])

# label the y to be the Impressions:
<ol>
(going to be predicted)

In [14]:
y = df["Impressions"].values

# Now we do not need those columns anymore

In [15]:
df.drop(columns=["Impressions"],inplace=True)

In [16]:
df.drop(columns=["Caption","Hashtags"],inplace=True)

# applying the rest of the data set to variable A

In [17]:
A = df.values

# horizontal stacking the Z,V and A variables

In [18]:
new = hstack([Z,V,A])

# new contains sparse matrix of captions and hashtags + rest of the data set

In [19]:
new

<COOrdinate sparse matrix of dtype 'float64'
	with 5299 stored elements and shape (102, 725)>

# applying new to X

In [20]:
X = new

# trying the linear reagression algo:

In [21]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42)

In [22]:
lr = LinearRegression()

In [23]:
lr.fit(X_train,y_train)

LinearRegression()

In [24]:
pre = lr.predict(X_test)

# its score is 0.98 could be better!

In [25]:
lr.score(X_test,y_test)

0.9812132928162682

In [26]:
df.head()

From Home  From Hashtags  From Explore  From Other  Saves  Comments  \
0       2586           1028           619          56     98         9   
1       2727           1838          1174          78    194         7   
2       2085           1188             0         533     41        11   
3       2700            621           932          73    172        10   
4       1704            255           279          37     96         5   

   Shares  Likes  Profile Visits  Follows  
0       5    162              35        2  
1      14    224              48       10  
2       1    131              62       12  
3       7    213              23        8  
4       4    123               8        0

# now with the prediction phase:

In [42]:
numerical_features = np.random.rand(725).tolist()

In [43]:
lr.predict(np.array(numerical_features).reshape(1,-1))

array([123.84048784])

In [44]:
Z.shape

(102, 551)

In [45]:
df.head()

From Home  From Hashtags  From Explore  From Other  Saves  Comments  \
0       2586           1028           619          56     98         9   
1       2727           1838          1174          78    194         7   
2       2085           1188             0         533     41        11   
3       2700            621           932          73    172        10   
4       1704            255           279          37     96         5   

   Shares  Likes  Profile Visits  Follows  
0       5    162              35        2  
1      14    224              48       10  
2       1    131              62       12  
3       7    213              23        8  
4       4    123               8        0

In [46]:
y

array([ 3920,  5394,  4021,  4528,  2518,  3884,  2621,  3541,  3749,
        4115,  2218,  3234,  4344,  3216,  9453,  5055,  4002,  3169,
        6168,  2407,  2064,  3973,  7281,  3052,  4628,  4082,  5394,
        2766,  3924,  3015,  6666,  3854,  4355,  4343,  6108,  2523,
        2327,  3990,  2191,  1941, 16062,  4998,  4289,  3880,  3786,
        4298,  3630,  2826,  7407, 10386,  2998,  7018,  2941,  6432,
       10667,  3988,  4978,  3388,  4467,  3246,  5072,  6339,  4239,
        3454,  7571,  3333,  3818, 10933,  5058,  3601,  3480,  3525,
        3606,  5542,  6559,  3623, 10493,  4446,  2957,  5538,  4681,
        5273,  5409,  5323,  8001,  4150,  4609,  6348, 11068,  7231,
       17396,  6814, 17713,  5563,  4842, 11149, 10206, 13700,  5731,
        4139, 32695, 36919], dtype=int64)

# Linear SVR algo:
<ol>
going to apply another algorithm on this data set so it can be more accurate

In [47]:
svr = LinearSVR()

In [48]:
X_train.shape

(76, 725)

In [49]:
y_train.shape

(76,)

In [50]:
svr.fit(X_train,y_train)

LinearSVR()

In [51]:
pr = svr.predict(X_test)

# This model can work better

In [52]:
svr.score(X_test,y_test)

0.9994477032090925

# prediction is more accurte

In [53]:
numerical_features = np.random.rand(725).tolist()

In [54]:
svr.predict(np.array(numerical_features).reshape(1,-1))

array([1.03623257])